version: '3.7'

services:

  db:
    image: mysql
    ports:
      - 3308:3306
    container_name: cool_sql
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: Library
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

  webapp:
    build: .
    ports:
      - 8181:8080
    restart: always
    container_name: webapp
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
