version: '3.7'

volumes:
  data:

services:
  db:
    image: mysql:8.0.22
    ports:
      - 3308:3306
    volumes:
      - data:/var/lib/mysql
    container_name: cool_mysql
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: Library
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  web:
    build: .
    ports:
      - 8181:8080
    container_name: super_webapp
    restart: always
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m29s
      timeout: 9s
      retries: 4
      start_period: 43s