spring:
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
    non-blocking-redelivery: true
    packages:
      trust-all: true
      trusted: com.epam.dmivapi.messaging, java.lang
  jms:
    listener:
      acknoledge-mode: auto
      auto-startup: true
      concurrency: 1
      max-concurrency: 1
    pub-sub-domain: false # false for point-to-point
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true